README.md
conda.recipe/meta.yaml
docs/installation.md

This has been tested on ml003/ml007.

add bioconda package recipe; improve installation in document

---

.github/labels.yml
.github/release-drafter.yml
.github/workflows/labeler.yml
.github/workflows/release.yml
pyproject.toml
setup.cfg

- add workflow for release automation
- add workflow for label setup and automation

add release automation

---

.gitignore
conda/README.md
noxfile.py
pyrovelocity/_trainer.py
pyrovelocity/_velocity.py
pyrovelocity/_velocity_model.py
pyrovelocity/_velocity_module.py
pyrovelocity/api.py
pyrovelocity/cytotrace.py
pyrovelocity/data.py
pyrovelocity/plot.py
pyrovelocity/utils.py

Update some type annotations based on the stacktrace and runtime types from fig2_pancreas_data.py . See description in associated issue: resolves #23 .

update type annotations based on calls from `fig2_pancreas_data.py`

---

.github/workflows/release.yml
.github/workflows/tests.yml
noxfile.py
pyrovelocity/__init__.py
setup.cfg
setup.py
tests/test_api.py
tests/test_cytotrace.py
tests/test_data.py
tests/test_plot.py
tests/test_pyrovelocity.py
tests/test_trainer.py
tests/test_utils.py
tests/test_velocity.py
tests/test_velocity_guide.py
tests/test_velocity_model.py
tests/test_velocity_module.py

- fundamental checks for breakage of loading library modules
- run coverage/pytest in Tests workflow
resolves #29

add tests to validate module load

---

README.md
poetry.lock
pyproject.toml
pyrovelocity/plot.py
reproducibility/figures/fig3/fig3.py
reproducibility/figures/fig3/fig3_uni_bifurcation_model2.py
reproducibility/figures/suppfig5/model1/fig3_allcells_model1.py
reproducibility/figures/suppfig5/model1/fig3_uni_bifurcation_model1.py
reproducibility/figures/suppfig5/model2/fig3_unipotent_mono_model2.py
reproducibility/figures/suppfig5/model2/fig3_unipotent_neu_model2.py
reproducibility/figures/suppfig5/suppfig5.py
setup.py

- update poetry
- add method to install gpu-compatible torch
- update documentation
resolves #33

update build process

---

.readthedocs.yml
pyproject.toml

release `v0.1.1`

---

reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/fig2/figure.py
reproducibility/figures/template-config.yaml

add uncertainty analysis boxplot for the kinetics parameters

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
pyrovelocity/_velocity.py
pyrovelocity/cytotrace.py
pyrovelocity/utils.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/template-config.yaml
reproducibility/figures/train.py
reproducibility/figures/zenconfig.py
reproducibility/figures/zenconfig.yaml

add model summary configuration in hydra-zen

---

pyrovelocity/_velocity.py
pyrovelocity/plot.py
pyrovelocity/utils.py
reproducibility/figures/config.yaml
reproducibility/figures/polar_histogram.py
reproducibility/figures/preprocess.py
reproducibility/figures/summarize.py
reproducibility/figures/template-config.yaml

produce summary plots package for all data sets

---

pyrovelocity/_velocity_model.py
pyrovelocity/_velocity_module.py
pyrovelocity/utils.py

refactor velocity model

---

pyrovelocity/_velocity.py
pyrovelocity/plot.py
pyrovelocity/utils.py
reproducibility/figures/dvc.lock
reproducibility/figures/summarize.py
reproducibility/figures/train.py

We reduced previous .pkl file by precomputing a set of metrics and posterior means for visualization function.

Reduced pkl file

---

conda/colab/construct.yaml
docs/history.md
docs/source/notebooks/pyrovelocity_colab_template.ipynb
pyproject.toml

release `v0.1.2`

---

pyrovelocity/config.py
reproducibility/figures/config.yaml
reproducibility/figures/data_download.py
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml

add pipeline stage for generating simulated data

---

pyrovelocity/config.py
pyrovelocity/data.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/models/medium_model1/run_info.json
reproducibility/figures/models/medium_model2/run_info.json
reproducibility/figures/reports/medium_model1/.gitignore
reproducibility/figures/reports/medium_model2/.gitignore

add pipeline stages for plotting simulated data

---

pyrovelocity/metrics/criticality_index.py
tests/metrics/test_criticality_index.py

add function to estimate criticality index

---

.gcloudignore
.github/workflows/deploy.yml
Makefile
app/environment-local.yml
cloudbuild.yaml
dockerfiles/Dockerfile
dockerfiles/Dockerfile.app
dockerfiles/Dockerfile.app.local
reproducibility/environment/README.md

build and deploy review application

---

.github/workflows/deploy.yml

automate deployment of review application

---

pyrovelocity/_velocity.py
reproducibility/figures/README.md
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/fig2/figure_extras.py
reproducibility/figures/summarize.py

…arison across dynamic and static dataset

add figures for shared time uncertainty

---

reproducibility/figures/dvc.lock
reproducibility/figures/fig2/figure_extras.py

This is the commit that implements the figures for pca and original spaces.

update embedding space comparison

---

pyrovelocity/config.py
pyrovelocity/data.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.yaml
reproducibility/figures/preprocess.py

add transcript count threshold filtering

---

pyrovelocity/metrics/hypersphere_distribution_divergence.py

add hypersphere distribution divergence

---

pyrovelocity/config.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/figS3/figure_extras.py

add violin plots for uncertainty measurements

---

reproducibility/figures/dvc.lock

Automated commits for https://github.com/pinellolab/pyrovelocity/commit/e21580faa47215c32ce029c75301ba8001c4bbd8 created by CML.

CML PR for data/filter e21580fa

---

pyrovelocity/plot.py
reproducibility/figures/dvc.lock
reproducibility/figures/summarize.py
reproducibility/figures/upload_figures_drive.sh

add script to upload run data to drive

---

pyrovelocity/config.py
pyrovelocity/plot.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/reports/larry_tips_model2/.gitignore
reproducibility/figures/reports/pbmc10k_model2/.gitignore
reproducibility/figures/summarize.py

add cluster-conditional distribution plots

---

pyrovelocity/plot.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/fig3/figure.py
reproducibility/figures/summarize.py

update figure 3

---

.github/workflows/cml.yml
pyrovelocity/plot.py
pyrovelocity/plots/rainbow.py
reproducibility/figures/.gitignore
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/summarize.py

integrate gene selection with parameter distribution estimates

---

reproducibility/figures/dvc.lock

Automated commits for https://github.com/pinellolab/pyrovelocity/commit/08dc1b495581bfd9f764afee17404dbbdb25d4a8 created by CML.

CML PR for filter/two 08dc1b49

---

reproducibility/figures/dvc.lock

Automated commits for https://github.com/pinellolab/pyrovelocity/commit/846db56c0ed3431535f0cf9e669d420c69b3957d created by CML.

CML PR for filter/five 846db56c

---

reproducibility/figures/dvc.lock

Automated commits for https://github.com/pinellolab/pyrovelocity/commit/65945e62788b10b7534285a59e05bd56ccc2ed62 created by CML.

CML PR for filter/two 65945e62

---

pyrovelocity/config.py
reproducibility/figures/config.yaml
reproducibility/figures/dvc.lock
reproducibility/figures/dvc.yaml
reproducibility/figures/figS2/figure.py
reproducibility/figures/figS2/figure_extras.py

* add extra figS2 for pbmc68K gene projection
* remove multilineage in macro f1 analysis

compare PCA and UMAP Rayleigh on minimal gene set projection

---

.github/workflows/cml.yml
dockerfiles/Dockerfile
reproducibility/figures/upload_figures_drive.sh

updates for compatibility with cml 0.19.1

---

.github/workflows/cml.yml
poetry.lock
pyproject.toml

pin dvc >3.0

---

reproducibility/figures/dvc.lock

Automated commits for https://github.com/pinellolab/pyrovelocity/commit/91df43ab67278f00a710688b5ae24bd6ae2824a9 created by CML.

CML PR for master 91df43ab

---

conda/colab/construct.yaml
conda/environment-gpu.yml
docs/history.md
docs/source/notebooks/pyrovelocity_colab_template.ipynb
pyproject.toml

chore(release): `v0.1.3`

---

.devcontainer/devcontainer.json
.dockerignore
.envrc.example
.gitignore
.vscode/extensions.json
.vscode/settings.json
Makefile
dockerfiles/Dockerfile.conda
justfile

refactor: update dev container and pod

---

.bazelrc
.github/workflows/cid.yaml
.gitignore
CHANGELOG.md
MODULE.bazel
MODULE.bazel.lock
Makefile
conda/colab/construct.yaml
containers/gpu.Dockerfile
containers/pkg.Dockerfile
docs/source/notebooks/pyrovelocity_colab_template.ipynb

feat(ci): add shared test cache

---

.github/actions/build_nix_image/action.yml
.github/workflows/cid.yaml
.pre-commit-config.yaml
Makefile
dev/cluster/pyrovelocity/nixbuild.cue
dev/cluster/pyrovelocity/nixbuild/templates/config.cue
dev/cluster/pyrovelocity/nixbuild/templates/pvc.cue
flake.lock
flake.nix
nix/containers/code.nix
nix/containers/default.nix
nix/containers/jupyter.nix

fix(flake): push images to artifact registry

---

.argo/nix.yaml
.devcontainer/devcontainer.json
.github/workflows/cid.yaml
MODULE.bazel
Makefile
README.md
conda/colab/construct.yaml
conda/rattler/recipe.yaml
containers/gpu.Dockerfile
containers/pkg.Dockerfile
docs/source/notebooks/pyrovelocity_colab_template.ipynb
flake.lock
flake.nix
nix/containers/code.nix
nix/containers/default.nix
nix/containers/jupyter.nix
pyproject.toml
scripts/conda

fix(images): use layer compression and composition to speed up builds

---

src/pyrovelocity/io/serialization.py
src/pyrovelocity/tests/io/test_serialization.py
src/pyrovelocity/utils.py

feat(io): (de)serialize anndata objects

---

MODULE.bazel
Makefile
conda/colab/construct.yaml
containers/gpu.Dockerfile
containers/pkg.Dockerfile
docs/source/notebooks/pyrovelocity_colab_template.ipynb
pyproject.toml
scripts/conda
src/pyrovelocity/tests/plots/conftest.py

fix(tests): use importlib resources to refer to fixture data

---

MODULE.bazel
Makefile
conda/colab/construct.yaml
containers/gpu.Dockerfile
containers/pkg.Dockerfile
docs/source/notebooks/pyrovelocity_colab_template.ipynb
pyproject.toml
scripts/conda
src/pyrovelocity/io/sparsity.py
src/pyrovelocity/tasks/preprocess.py
src/pyrovelocity/tests/conftest.py
src/pyrovelocity/workflows/main_configuration.py
src/pyrovelocity/workflows/main_workflow.py

feat(workflows): add dataclass for preprocessing outputs interface

---

src/pyrovelocity/workflows/main_workflow.py

feat(workflows): add configuration for pons data

---

src/pyrovelocity/workflows/cli/execute.py
src/pyrovelocity/workflows/main_configuration.py
src/pyrovelocity/workflows/main_workflow.py

feat(workflows): add configuration for human bone marrow data

---

reproducibility/figures/archive/pv/cytotrace.py
src/pyrovelocity/analysis/cytotrace.py
src/pyrovelocity/tests/analysis/test_cytotrace.py

fix(cytotrace): add smoke test module

---

.github/workflows/cid.yaml
MODULE.bazel
MODULE.bazel.lock
Makefile
conda/colab/construct.yaml
containers/gpu.Dockerfile
containers/pkg.Dockerfile
docs/source/notebooks/pyrovelocity_colab_template.ipynb
pyproject.toml
scripts/conda
src/pyrovelocity/workflows/cli/execution_utils.py
src/pyrovelocity/workflows/main_configuration.py
src/pyrovelocity/workflows/main_workflow.py

fix: support workflow execution for any data subset

---

.github/labels.yml
.github/workflows/cid.yaml
.github/workflows/run-workflow.yaml
MODULE.bazel
Makefile
conda/colab/construct.yaml
containers/gpu.Dockerfile
containers/pkg.Dockerfile
docs/source/notebooks/pyrovelocity_colab_template.ipynb
nix/pkgs/default.nix
pyproject.toml
scripts/conda
src/pyrovelocity/analysis/analyze.py
src/pyrovelocity/io/datasets.py
src/pyrovelocity/models/_velocity.py
src/pyrovelocity/plots/_vector_fields.py
src/pyrovelocity/random_state.py
src/pyrovelocity/tasks/data.py
src/pyrovelocity/tasks/evaluate.py
src/pyrovelocity/tasks/postprocess.py
src/pyrovelocity/tasks/preprocess.py
src/pyrovelocity/tasks/summarize.py
src/pyrovelocity/tasks/train.py
src/pyrovelocity/tests/test_random_state.py
src/pyrovelocity/workflows/constants.py
src/pyrovelocity/workflows/main_configuration.py
src/pyrovelocity/workflows/main_workflow.py

fix: set random seeds from global constant
